version: '3'
services:
  eureka-server:
    image: springcloud/eureka:latest
    ports:
      - "8761:8761"
  movie-info:
    build: ./movie-info-service
    ports:
      - "8082:8082"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server

  movie-rating:
    build: ./movie-rating-service
    ports:
      - "8083:8083"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server

  movie-catalog:
    build: ./movie-cataloge-service
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server

networks:
  demo-microservice: